import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/providers/Provider";
import clsx from "clsx";
import { fontSans } from "@/config/fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en" suppressHydrationWarning>
      <body  className={clsx("font-sans antialiased", fontSans.className)}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
